<div style="width: 100%; clear: both;">
    <div style="float: left; width: 50%;">
       <img src="https://www.uoc.edu/content/dam/news/images/noticies/2016/202-nova-marca-uoc.jpg", align="left">
    </div>
</div>

<div style="float: right; width: 50%;">
    <p style="margin: 0; padding-top: 22px; text-align:right;">22.501 · Fundamentos de Programación</p>
    <p style="margin: 0; text-align:right;">Grado en Ciencia de Datos Aplicada</p>
    <p style="margin: 0; text-align:right; padding-button: 100px;">Estudios de Informática, Multimedia y Telecomunicación</p>
</div>

</div>
<div style="width: 100%; clear: both;">
<div style="width:100%;">&nbsp;</div>

Fundamentos de Programación
============================

PEC 6 Preprocesamiento de datos en Python.
-----------------------------------------------------

En este Notebook se encontraréis el conjunto de actividades evaluables como PEC de la asignatura. Veréis que cada una de ellas tiene asociada una puntuación, que indica el peso que tiene la actividad sobre la nota final de la PEC. Adicionalmente, hay un ejercicio opcional, que no tiene puntuación dentro de la PEC, pero que se valora al final del semestre de cara a conceder las matrículas de honor y redondear las notas finales. Podréis sacar la máxima nota de la PEC sin necesidad de hacer este ejercicio. El objetivo de este ejercicio es que sirva como pequeño reto para los estudiantes que quieran profundizar en el contenido de la asignatura.

Veréis que todas las actividades de la PEC tienen una etiqueta, que indica los recursos necesarios para llevarla a cabo. Hay tres posibles etiquetas:

* <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">NM</span> **Sólo materiales**: las herramientas necesarias para realizar la actividad se pueden encontrar en los materiales de la asignatura.

* <span style = "font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span> **Consulta externa guiada**: la actividad puede requerir hacer uso de herramientas que no se encuentran en los materiales de la asignatura, pero el enunciado contiene indicaciones de dónde o cómo encontrar la información adicional necesaria para resolver la actividad.

* <span style = "font-family: Courier New; background-color: #f2ae72; color: #000000; padding: 3px;">EI</span> **Consulta externa independiente**: la actividad puede requerir hacer uso de herramientas que no se encuentran en los materiales de la asignatura, y el enunciado puede no incluir la descripción de dónde o cómo encontrar esta información adicional. Será necesario que el estudiante busque esta información utilizando los recursos que se han explicado en la asignatura.

Es importante notar que estas etiquetas no indican el nivel de dificultad del ejercicio, sino únicamente la necesidad de consulta de documentación externa para su resolución. Además, recordad que las **etiquetas son informativas**, pero podréis consultar referencias externas en cualquier momento (aunque no se indique explícitamente) o puede ser que podáis hacer una actividad sin consultar ningún tipo de documentación. Por ejemplo, para resolver una actividad que sólo requiera los materiales de la asignatura, puedéis consultar referencias externas si queréis, ya sea tanto para ayudaros en la resolución como para ampliar el conocimiento!

En cuanto a la consulta de documentación externa en la resolución de los ejercicios, recordad **citar siempre la bibliografía utilizada** para resolver cada actividad.

---

# Ejercicio 1


En este ejercicio trabajaremos con el dataset de recetas **'recetasdelaabuela.csv'**, publicada por la organización [somosnlp](https://somosnlp.org/), y que encontraréis en el directorio `/data` de la entrega. Nuestro objetivo es realizar una exploración inicial para comprender la estructura del conjunto de datos y responder algunas preguntas utilizando técnicas básicas de análisis con Python.  **(2 puntos)**

a)  Carga el dataset en un DataFrame de `pandas` y muestra las primeras 3 filas.  Muestra el nombre de todas las columnas del dataset. Muestra las dimensiones del dataset (número de filas y columnas).

**(0,25 puntos)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [6]:
# Respuesta
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
ruta_archivo = "/content/drive/MyDrive/Colab_Notebooks" \
               "/prog_datasci_6/data/recetasdelaabuela.csv"

# a) Cargamos el dataset y exploramos contenidos
data = pd.read_csv(ruta_archivo)
print("Primeras 3 filas del dataset:")
print(data.head(3))

print("\nNombres de las columnas:")
print(data.columns)

print("\nDimensiones del dataset:")
print(data.shape)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Primeras 3 filas del dataset:
   Id                                             Nombre  \
0   1                                Berenjenas rellenas   
1   2              Alcachofas al horno con pico de gallo   
2   3  Arroz basmati salteado con Heura y verduras va...   

                                                 URL  \
0  https://www.elmueble.com/cocinas/comidas-salud...   
1  https://www.elmueble.com/cocinas/comidas-salud...   
2  https://www.elmueble.com/cocinas/comidas-salud...   

                                        Ingredientes  \
0  2 berenjenas, 1 pimiento rojo, 1 pimiento amar...   
1  4 alcachofas, 1 limón, 400 g de carne picada (...   
2  200 g de arroz basmati integral, 450 ml de agu...   

                                               Pasos    Pais Duracion  \
0  Paso 1. Lava bien las berenjenas y pártelas po...  España   45 min   
1  P

b) Identifica el tipo de dato de cada columna.  Calcula el número de valores nulos por columna, expresado tanto en números absolutos como en porcentajes usando solo un decimal.

**(0,5 puntos)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [7]:
# Respuesta
# b) Tipos de datos y valores nulos
print("Tipos de datos por columna:")
print(data.dtypes)

# Obtenemos valores nulos por columna en absolutos. Al aplicar .sum() sobre los
# valores booleanos (True = 1, False = 0), se obtiene el número total de
# valores True (i.e., NaN) en cada columna.
nulos_abs = data.isnull().sum()
# Obtenemos valores nulos por columna en porcentajes dividiendo por el total
nulos_pct = (nulos_abs / len(data) * 100).round(1)
print("\nNúmero de valores nulos por columna (absolutos y porcentaje):")
# Creamos un diccionario con los datos. No hay dos diccionarios separados.
# nulos_abs y nulos_pct son dos variables que están siendo combinadas en un
# único diccionario para crear el DataFrame.
data_dict = {"nulos_abs": nulos_abs,
             "nulos_pct": nulos_pct}
# Creamos el DataFrame a partir del diccionario
df_nulos = pd.DataFrame(data_dict)
# Imprimimos el DataFrame
print(df_nulos)

Tipos de datos por columna:
Id                      int64
Nombre                 object
URL                    object
Ingredientes           object
Pasos                  object
Pais                   object
Duracion               object
Porciones              object
Calorias              float64
Categoria              object
Contexto               object
Valoracion y Votos     object
Comensales             object
Tiempo                 object
Dificultad             object
Categoria 2            object
Unnamed: 16           float64
Unnamed: 17           float64
Unnamed: 18            object
dtype: object

Número de valores nulos por columna (absolutos y porcentaje):
                    nulos_abs  nulos_pct
Id                          0        0.0
Nombre                      0        0.0
URL                         0        0.0
Ingredientes              209        1.0
Pasos                       2        0.0
Pais                      496        2.5
Duracion                 6833       34

c) Renombra columnas automáticamente para estandarizar nombres y hacerlos más manejables.

- Elimina espacios al inicio y al final.
- Convierte a minúsculas.
- Reemplaza espacios por guiones bajos.
- Elimina caracteres no alfabéticos, manteniendo los números.


**(1 punto)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>


In [8]:
# Respuesta
# c) Renombramos columnas
data.columns = (
    data.columns
    .str.strip()              # Eliminamos espacios al inicio y final
    .str.lower()              # Convertimos a minúsculas
    .str.replace(" ", "_")    # Reemplazamos espacios con guiones bajos
    .str.replace(r"[^a-zA-Z0-9_]", "", regex=True)
    # El prefijo r indica que es una cadena raw (sin escapes adicionales en
    # caracteres, e.g. \), lo cual es estándar para regex.
    # El símbolo ^ en de los corchetes indica "ninguno de estos caracteres",
    # i.e., niega el conjunto de estos caracteres. Así, busca el resto.
    # a-zA-Z0-9_ especifica el rango de caracteres permitidos.
    # "" especifica que los caracteres encontrados (que no son letras, números
    # o guiones bajos) deben ser reemplazados por nada, i.e., eliminados.
    # El argumento regex=True asegura que usamos una expresión regular.
    # Nota: esto se aplica solamente a los nombres de la columnas, no valores.
)
print("Nombres de las columnas tras renombrar:")
print(data.columns)

Nombres de las columnas tras renombrar:
Index(['id', 'nombre', 'url', 'ingredientes', 'pasos', 'pais', 'duracion',
       'porciones', 'calorias', 'categoria', 'contexto', 'valoracion_y_votos',
       'comensales', 'tiempo', 'dificultad', 'categoria_2', 'unnamed_16',
       'unnamed_17', 'unnamed_18'],
      dtype='object')


d) Borra  las columnas que tengan valores nulos para todas las filas.

**(0,25 puntos)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>


In [9]:
# Respuesta
# d) Eliminar columnas completamente nulas
# dropna() elimina filas o columnas con valores nulos.
# El parámetro axis=1 indica que la operación debe realizarse en las
# columnas (axis=0 aplicaría a las filas).
# El parámetro how="all" especifica que solo se eliminarán las columnas que
# contengan solamente valores nulos.
data = data.dropna(axis=1, how="all")
print("Dimensiones tras eliminar columnas completamente nulas:")
print(data.shape)

Dimensiones tras eliminar columnas completamente nulas:
(20085, 16)


# Ejercicio 2

Observa los valores de las siguientes columnas:

- Duración
- Categoria
- Valoración y votos
- Comensales
- Categoría 2

Veremos que no podemos trabajar con ellas a no ser que hagamos algun tipo de preprocesado para que sean tratables. Para que estas columnas sean tratables, es necesario realizar un preprocesado que implique limpieza y transformación de los datos.

**(4,5 puntos)**

a) Observa la variable `Duración`. Extrae la duración total en minutos.
Convierte a formato numérico para facilitar análisis.

Muestra las últimas 260 filas comparando la columna original y la columna procesada.


Nota, considera el uso de [RegEx](https://www.w3schools.com/python/python_regex.asp)


**(1,5 punto)**   <span style="fuente-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span>  

In [10]:
# Respuesta
import pandas as pd
import re
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
ruta_archivo = "/content/drive/MyDrive/Colab_Notebooks" \
               "/prog_datasci_6/data/recetasdelaabuela.csv"
data = pd.read_csv(ruta_archivo)

# Normalizamos columnas como anteriormente
data.columns = (
    data.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace(r"[^a-zA-Z0-9_]", "", regex=True))

# Inspeccionamos valores únicos de la columna 'duracion'
print("Valores únicos de la columna duracion:")
print(data["duracion"].unique())


def convert_duracion_a_min(duracion):
    if pd.isnull(duracion):
        return np.nan
    # Normalización básica por si hay espacios adicionales
    duracion = duracion.strip().lower()
    # Extraemos horas y minutos mediante RegEx
    horas = re.search(r"(\d+)\s*h", duracion)
    # (\d+) busca uno o más dígitos consecutivos (\d+).
    # Los paréntesis () capturan estos dígitos para que puedan extraerse más
    # adelante como un grupo.
    # \s* permite la presencia de cero o más espacios en blanco (\s), e.g.,
    # "45m" y "45 m" serán válidos.
    # [mM] busca la letra "m", ya sea en minúscula (m) o mayúscula (M),
    # asegurando capturar todas la m.
    # Devuelve un objeto Match si encuentra una coincidencia; de lo contrario,
    # devuelve None.
    minutos = re.search(r"(\d+)\s*[mM]", duracion)
    total_minutos = 0
    if horas:
      # horas.group(1) captura el número de horas que ha encontrado la
      # expresión regular, donde group(1) hace referencia al primer grupo de la
      # expresión regular (el número de horas).
      # Así, si e.g. "duracion = "2 h 30 m"", group(1) extrae el primer grupo
      # de la coincidencia. En este caso, el grupo es el número de horas,
      # que es "2". Esto es lo que hace group(1).
      # "int(horas.group(1)) * 60" convierte las horas a minutos mediante * 60.
      # total_minutos acumula el valor calculado, i.e., a los minutos
      # acumulados hasta ese momento, se les añade la cantidad de minutos
      # correspondientes a las horas extraídas.
        total_minutos += int(horas.group(1)) * 60 # Convierte horas a minutos
    if minutos:
        total_minutos += int(minutos.group(1)) # Agrega minutos
    return total_minutos

# Aplicamos la función a la columna duracion
duracion_min = data["duracion"].apply(convert_duracion_a_min)
data["duracion_min"] = duracion_min
# Mostrar últimas 260 filas comparando ambas columnas
print("\nÚltimas 260 filas (duracion original y procesada):")
print(data[["duracion", "duracion_min"]].tail(260))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Valores únicos de la columna duracion:
['45 min' '60 min' '40 min' '30 min' '25 min' '10 min' '80 min' '15 min'
 '55 min' '5 min' '20 min' '40 m' '15 m' '50 m' '30 m' '25 m' '20 m'
 '45 m' '35 m' '1 h' '1 h 20 m' '55 m' '29 m' '10 m' '1 h 15 m' '19 m'
 '1 h 40 m' '1 h 10 m' '26 m' '1 h 30 m' '2 h 45 m' nan '1h 30m' '45m'
 '15m' '4h' '30m' '2h 30m' '24h' '10m' '8h' '6h' '3h' '2 h' '1h' '1h 30 m'
 '1h 15 m' '1h15' '1h20m' '1h 15' '1h 20 m' '60 m' '40m' '1hr' '2h 30 m'
 '20mi' '2 h 30 m' '90 m' '1 h 30m' '20m' '7 m' '5 m' '1h 45m' '8 m' '4 h'
 '25 ms' '30 ms' '1 h m' '3 h' '45ms' '1 30 m' '1h 45 m' '20 ms'
 '1 hr 30 m' '35m' '130 m' '1 H' '25m' '140 m' '6 h' '40 a 45 m' '1h 40 m']

Últimas 260 filas (duracion original y procesada):
       duracion  duracion_min
19825      30 m          30.0
19826      30 m          30.0
19827       1 h          60.0
19828       

b) Observa la variable `Categoría`. Modifica la variable de forma que solo aparezca la primera categoría de la cada lista.

Rellena los valores faltantes con `NaN`.

**(0,5 puntos)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [11]:
# Respuesta
# Función para procesar valores de categoría
def procesar_categoria(valor):
    """
    Esta función procesa los valores de la columna 'categoria' de un dataset.
    Los valores pueden estar en formato de lista (e.g. ['Recetas mexicana',
    'Recetas peruana']) o ser cadenas simples (e.g. ['Recetas mexicanas']).
    La función realiza los siguientes pasos:
    - Si el valor es NaN o una lista vacía, devuelve NaN.
    - Si el valor es una lista no vacía, elimina los corchetes y las comillas,
      y procesa el valor.
    - Si el valor contiene múltiples categorías separadas por comas,
      toma solo la primera.
    valor (str): valor de la categoría a procesar. Devuelve str o np.nan, i.e.,
    la 1r categoría procesada o NaN si no es válido.

    Caso 1: si el valor es NaN o una lista vacía "[]", devolvemos NaN.
    Verificamos si el valor es NaN o si es una lista vacía "[]".
    """
    if pd.isnull(valor) or valor.strip() == "[]":
        return np.nan

    """
    Caso 2: limpiamos y procesamos categorías válidas.
    Eliminamos los corchetes ("[]") y las comillas simples (') de la cadena.
    Además, aplicamos el método strip() para quitar espacios en blanco extra
    alrededor del valor.
    """
    valor_limpio = valor.strip("[]").replace("'", "").strip()
    # Si el valor limpio queda vacío, devolvemos NaN.
    # Esto es útil para manejar casos donde el valor es una lista vacía o una
    # cadena con solo espacios.
    if not valor_limpio:
        return np.nan

    """
    Caso 3: tomamos la primera categoría si hay múltiples. Si el valor contiene
    varias categorías separadas por comas, tomamos solo la primera.
    Esto es útil cuando la categoría contiene más de una opción, e.g.,
    "Recetas mexicanas, Recetas peruanas".
    """
    return valor_limpio.split(",")[0].strip()

# Aplicamos la función a la columna "categoria".
# Utilizamos la función 'apply' para aplicar 'procesar_categoria' a cada
# elemento de la columna 'categoria'.
categoria_procesada = data["categoria"].apply(procesar_categoria)
data["categoria_procesada"] = categoria_procesada

# Verificamos resultados: valores únicos procesados.
# Mostramos los valores únicos de la columna "categoria_procesada".
print("Valores únicos en categoría procesada:")
print(data["categoria_procesada"].unique())

# Mostramos un subconjunto de datos transformados, incluyendo celdas vacías.
# Se selecciona el rango de filas 971:985.
print("\nEjemplo de transformación (categoría original y procesada):")
print(data[["categoria", "categoria_procesada"]].iloc[971:985])

Valores únicos en categoría procesada:
[nan 'Receta sin gluten' 'Recetas al horno'
 'Recomendada para vegetarianos' 'Recetas chilenas' 'Recetas peruanas'
 'Receta sin lactosa' 'Recetas mexicanas' 'Recetas indias'
 'Recomendada para perder peso' 'Receta sin azúcar' 'Receta sin sal'
 'Recomendada para veganos' 'Recetas para Navidad' 'Recetas venezolanas'
 'Recetas españolas' 'Recetas al vapor' 'Recetas chinas'
 'Recetas para Semana Santa' 'Recetas al microondas' 'Recetas argentinas'
 'Recetas para San Valentín' 'Recetas colombianas' 'Recetas japonesas'
 'Recetas italianas' 'Recetas para Año Nuevo']

Ejemplo de transformación (categoría original y procesada):
                                             categoria  \
971                               ['Recetas al horno']   
972                                                 []   
973  ['Recomendada para vegetarianos', 'Recetas al ...   
974  ['Recomendada para vegetarianos', 'Recomendada...   
975                                          

c) Observa la variable `Valoración y votos`. Divide la variable en dos columnas:

- Valoración: Un valor numérico flotante (e.g., 4.5).
- Votos: Un valor entero que representa la cantidad de votos (e.g., 200).

Rellena los valores faltantes con `NaN`.

Comprueba el código mostrando por pantalla los indices `19015:19029` para las columnas `valoracionyvotos`, `valoracion` y `votos`.


**(0,5 puntos)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [12]:
# Respuesta
import pandas as pd
import numpy as np
import re

def procesar_valoracion_y_votos(valoracion_votos):
    """
    Función para procesar la columna 'valoracion_y_votos'.
    Esta función extrae la valoración y los votos de una cadena de texto.
    Devuelve NaN si no se extrae la información correctamente.

    Caso 1: si el valor es NaN o está vacío, devolvemos NaN para ambas columnas.
    Verificamos si el valor es NaN o si el campo está vacío (NaN).
    En cualquiera de estos casos, devolvemos NaN en ambas columnas.
    """
    if pd.isnull(valoracion_votos):
        return np.nan, np.nan

    """
    Caso 2: extraemos valoración y votos utilizando regex.
    Usamos 're.findall' para buscar un patrón que extraiga primero los valores
    numéricos de la valoración
    (con decimales permitidos) y después el número de votos (un número entero).
    El patrón '([\d.]+).*?(\d+)' busca un número flotante (valoración) seguido
    de un número entero (votos).

    [\d.] indica que estamos buscando cualquier dígito (\d, que equivale a
    [0-9]) o un punto (.), ya que un número decimal puede tener puntos decimales.
    + significa "uno o más" de los caracteres anteriores, i.e., buscará una
    secuencia de dígitos o puntos. Esto captura la valoración (e.g., 4.5 o 3).
    En ").*?" ) cierra el primer grupo de captura (la valoración).
    En ".*?" el punto (.) significa "cualquier carácter", y el *? indica
    "cero o más veces de manera no codiciosa" (es decir, el patrón buscará la
    menor cantidad de caracteres posibles que coincidan). Este fragmento ayuda
    a descartar cualquier texto entre la valoración y los votos,
    hasta llegar a la siguiente parte relevante.
    (\d+) busca un número entero (sin decimales).
    \d representa cualquier dígito, y el
    + significa "uno o más" dígitos. Este fragmento captura los votos.
    """
    resultado = re.findall(r"([\d.]+).*?(\d+)", valoracion_votos)

    """
    Caso 3: si encontramos el patrón, devolvemos la valoración como un número
    flotante y los votos como un entero.
    Si no encontramos el patrón esperado, devolvemos NaN para ambas columnas.
    resultado[0][0] corresponde a la valoración (el 1r valor numérico
    extraído de la cadena).
    resultado[0][1] corresponde a los votos (el 2n valor
    extraído de la cadena).
    E.g., si el resultado[0][0] es 0 y resultado[0][1] es un valor mayor que 0,
    significa que sólo se extrajo el número de votos correctamente,
    pero la valoración no se pudo extraer, lo que también generará NaN para la
    valoración y el valor correcto para los votos.
    """
    if resultado:
        valoracion = resultado[0][0]
        votos = resultado[0][1]
        return float(valoracion), int(votos)

    return np.nan, np.nan

# Aplicamos la función 'procesar_valoracion_y_votos' a cada fila de la columna
# 'valoracion_y_votos'.
# 'apply' aplica la función a cada valor en la columna, y 'pd.Series' convierte
# el resultado en dos columnas separadas.
valoracion_votos_procesados = data["valoracion_y_votos"].apply(
    lambda x: pd.Series(procesar_valoracion_y_votos(x)))

# Asignamos los resultados de las dos columnas (valoración y votos) a nuevas
# columnas en el DataFrame.
# 'valoracion' recibirá el 1r valor de la serie procesada, y 'votos' el 2n.
data["valoracion"] = valoracion_votos_procesados[0]
data["votos"] = valoracion_votos_procesados[1]

# Verificamos los resultados mostrando el rango 19015:19029.
print("\nÍndices 19015:19029 para las columnas procesadas:")
print(data.loc[19015:19029, ["valoracion_y_votos", "valoracion", "votos"]])


Índices 19015:19029 para las columnas procesadas:
                valoracion_y_votos  valoracion  votos
19015   Valoración: 3,8 (17 votos)         3.0    8.0
19016   Valoración: 3,9 (32 votos)         3.0    9.0
19017   Valoración: 3,3 (12 votos)         3.0    3.0
19018    Valoración: 3,6 (5 votos)         3.0    6.0
19019       Valoración: 3 (1 voto)         3.0    1.0
19020   Valoración: 4,8 (12 votos)         4.0    8.0
19021                          NaN         NaN    NaN
19022                          NaN         NaN    NaN
19023    Valoración: 3,8 (6 votos)         3.0    8.0
19024   Valoración: 4,5 (20 votos)         4.0    5.0
19025  Valoración: 4,1 (150 votos)         4.0    1.0
19026  Valoración: 4,4 (105 votos)         4.0    4.0
19027   Valoración: 4,1 (52 votos)         4.0    1.0
19028  Valoración: 4,7 (318 votos)         4.0    7.0
19029  Valoración: 4,4 (249 votos)         4.0    4.0


d) Observa la variable `Comensales`. Verificar si los valores son numéricos o si están en texto (e.g., "4 personas"). Convertir los valores a un formato numérico en una nueva variable `comensales_num`.

Rellena los valores faltantes con `NaN`.

Comprueba el código mostrando por pantalla los indices `19015:19029` para la columna sin procesar y la procesada.

**(1 punto)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [13]:
# Respuesta
import pandas as pd
import numpy as np
import re
# Función para procesar la columna 'comensales'
# Esta función toma un valor de la columna 'comensales' y extrae el número de
# comensales. Si el valor es NaN o no contiene un número válido, devolvemos NaN
def procesar_comensales(comensales):
    """
    Procesa los valores de la columna 'comensales'. Si el valor es un número
    válido, devuelve el número de comensales como un entero. Si no es posible
    extraer un número, devuelve NaN.
    # Caso 1: si el valor es NaN, devolvemos NaN.
    # Verificamos si el valor es NaN. En ese caso, devolvemos NaN.
    """
    if pd.isnull(comensales):
        return np.nan
    """
    Caso 2: extraemos el número de comensales usando una expresión regular
    Utilizamos regex para encontrar el primer número dentro del texto.
    """
    resultado = re.search(r"(\d+)", comensales)
    """
    Caso 3: si encontramos un número, lo devolvemos como entero.
    Si encontramos un número, lo convertimos a entero y lo devolvemos.
    """
    if resultado:
        comensales_num = int(resultado.group(1)) # Asignamos el nº de comensales
        return comensales_num

    # Si no encontramos un número, devolvemos NaN.
    return np.nan

# Aplicamos la función a la columna 'comensales'
# Usamos el método 'apply' para aplicar la función 'procesar_comensales' a cada
# fila de la columna 'comensales'
comensales_procesados = data["comensales"].apply(procesar_comensales)

# Creamos la nueva columna 'comensales_num'
# Asignamos los resultados procesados a la nueva columna 'comensales_num' del df
data["comensales_num"] = comensales_procesados

# Mostrar los índices solicitados
# Mostramos los valores de las columnas 'comensales' original y
# 'comensales_num' procesada para los índices de 19015 a 19029
print("\nÍndices 19015:19029 para la columna 'Comensales' procesada:")
print(data.loc[19015:19029, ["comensales", "comensales_num"]])


Índices 19015:19029 para la columna 'Comensales' procesada:
         comensales  comensales_num
19015  4 comensales             4.0
19016           NaN             NaN
19017           NaN             NaN
19018  4 comensales             4.0
19019           NaN             NaN
19020  4 comensales             4.0
19021    1 comensal             1.0
19022  4 comensales             4.0
19023  2 comensales             2.0
19024  4 comensales             4.0
19025  2 comensales             2.0
19026  4 comensales             4.0
19027  4 comensales             4.0
19028  5 comensales             5.0
19029  6 comensales             6.0


e) Observa la variable `Categoría 2`.  Cada fila incluye un texto que describe características de una receta separadas por comas. Estas características están clasificadas en tres categorías principales: "Sin", "Bajo", y "Alto" (por ejemplo, "Sin grasas trans", "Bajo en calorías", "Alto en fibra").  Además, algunos términos pueden no pertenecer a estas categorías.

Consigue construir una tabla tal como la siguiente, con las ocurrencias de cada término, clasificados por categoría y ordenados por frecuencia.  

|           |Categoria|  Termino         | Total|
|-----------|---------|------------------|------|
| 41        | sin     | sin grasa        | 7442 |
| 19        | bajo    | bajo en calorías | 7167 |
| 8         | alto    | alto en fibra    | 4172 |
| ...       | ...     | ....             | ...  |




**(1 punto)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [14]:
# Respuesta
import pandas as pd
from collections import Counter
def clasificar_y_contar(termino):
    """
    Clasifica y divide los términos en la columna 'categoria_2'. Si el valor es
    NaN, devuelve una lista vacía. Si no, separa los términos por comas y los
    limpia de espacios adicionales. Devuelve una lista de términos.
    Si el valor es NaN, devuelve una lista vacía.
    # Caso 1: si el valor es NaN, devolvemos una lista vacía.
    """
    if pd.isnull(termino):
        return []
    """
    # Caso 2: dividimos el término por comas y eliminamos espacios en blanco
    # adicionales. Utilizamos split para dividir y strip para limpiar.
    """
    return [t.strip() for t in termino.split(",")]
# Usamos 'apply' para aplicar la función 'clasificar_y_contar' a
# cada fila de la columna 'categoria_2'. Luego usamos 'explode' para separar
# cada término en una fila individual.
terminos = data["categoria_2"].dropna().apply(clasificar_y_contar).explode()
# Usamos 'Counter' para contar las veces que aparece cada
# término en la lista 'terminos'.
conteo_terminos = Counter(terminos)

# Iteramos sobre el diccionario de conteo y clasificamos cada término
# en una categoría.
clasificacion = []
for termino, total in conteo_terminos.items():
    # Caso 1: si el término empieza con "sin", lo clasificamos como "sin".
    if termino.lower().startswith("sin"):
        categoria = "sin"
    # Caso 2: si el término empieza con "bajo", lo clasificamos como "bajo".
    elif termino.lower().startswith("bajo"):
        categoria = "bajo"
    # Caso 3: si el término empieza con "alto", lo clasificamos como "alto".
    elif termino.lower().startswith("alto"):
        categoria = "alto"
    # Caso 4: si no empieza con "sin", "bajo" ni "alto", lo clasificamos
    # como "otros".
    else:
        categoria = "otros"
    clasificacion.append({"Categoria": categoria, "Termino": termino,
                          "Total": total})
# Creamos un DataFrame con la clasificación y lo ordenamos por la frecuencia
# de los términos.
df_clasificacion = pd.DataFrame(clasificacion).sort_values(by="Total",
                                                           ascending=False)
# Mostramos los primeros 10 términos clasificados por su frecuencia.
print("\nTabla de términos clasificados:")
print(df_clasificacion.head(10))


Tabla de términos clasificados:
   Categoria                   Termino  Total
4        sin                 Sin grasa   7441
3       bajo          Bajo en calorías   7167
0       alto             Alto en fibra   4171
1        sin          Sin grasas trans   2075
5       alto            Alto en grasas   1601
8       alto             Alto en sodio    828
11       sin        Sin azúcar añadida    676
12      alto  Alto en grasas saturadas    532
10       sin              Sin calorías    456
19      alto         Alto en proteínas    369


Ejercicio 3
=======

El conjunto de datos `data/diamonds.csv`  contiene los precios y otros atributos de casi 54,000 diamantes. Es un excelente conjunto de datos para proponernos practicar sobre imputación de datos.

Vamos a evaluar diferentes estrategias para la imputación de datos faltantes el conjunto de datos de diamantes, jugando con las variables  `carat`, `depth`, `table`, `price`, `x`, `y` y `z` del conjuto de datos en `data/diamonds.csv`. Puedes seguir estos pasos:

**(3,5 puntos)**



a) Crea un número aleatorio de valores perdidos en las variables especificadas, cubriendo el 20% de los valores. Comprueba que el porcentage de valores perdidos por variable coincide con el 20%. Guarda una copia del dataset original (sin valores perdidos) en `original_df`.

**(1 punto)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [20]:
# Respuesta
import pandas as pd
import numpy as np

# Montamos el drive y cargamos el dataset 'diamonds.csv'.
from google.colab import drive
drive.mount('/content/drive')
ruta_diamonds = "/content/drive/MyDrive/Colab_Notebooks" \
               "/prog_datasci_6/data/diamonds.csv"
df_original = pd.read_csv(ruta_diamonds)

# Definimos las columnas a modificar más adelante con valores NaN aleatorios.
columnas_a_modif = ["carat", "depth", "table", "price", "x", "y", "z"]

# Creamos una copia del dataset original para asegurar no alterar el original.
df = df_original.copy()

# Introducimos valores NaN en un 20% de las filas de cada columna seleccionada.
# Usamos una semilla fija para asegurar la reproducibilidad del experimento.
np.random.seed(42)
for column in columnas_a_modif:
    # Para calcular cuántos valores NaN debemos insertar en cada columna,
    # multiplicamos el 20% (0.2) por la longitud total de la
    # columna (len(df[column])).
    # Convertimos este valor a entero (int) ya que necesitamos un
    # número exacto de índices.
    n_faltante = int(0.2 * len(df[column]))
    # Para selecionar aleatoriamente los índices donde insertar los NaN,
    # usamos np.random.choice para elegir índices del df aleatoriamente.
    # Pasamos df.index para asegurar que los índices seleccionados
    # pertenecen al DataFrame.
    # El parámetro replace=False garantiza que no se seleccionen
    # índices repetidos.
    missing_indices = np.random.choice(df.index, n_faltante, replace=False)
    # Usamos df.loc para localizar las filas correspondientes a los índices
    # en 'missing_indices'. La selección de 'column' asegura que NaN se
    # asigne únicamente a la columna específica en cada iteración del bucle.
    # Esto permite controlar qué columnas se modifican sin afectar
    # al resto del DataFrame.
    df.loc[missing_indices, column] = np.nan

# Calculamos y mostramos el porcentaje de valores faltantes por columna en
# el DataFrame modificado.
porc_faltante = df[columnas_a_modif].isnull().mean() * 100
print("\nPorcentaje de valores perdidos por variable:")
print(porc_faltante)
# Verificamos las dimensiones del dataset original para confirmar que
# no ha sido alterado.
print("\nDimensiones del dataset original (sin valores perdidos):",
      df_original.shape)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Porcentaje de valores perdidos por variable:
carat    20.0
depth    20.0
table    20.0
price    20.0
x        20.0
y        20.0
z        20.0
dtype: float64

Dimensiones del dataset original (sin valores perdidos): (53940, 10)


b)  Seleccionar tres políticas para la imputación de datos faltantes mediante el método `SimpleImputer` del paquete [scikit-learn](https://scikit-learn.org/stable/).
Calcular el rendimiento de cada política de imputación para cada variable en términos de Root Mean Square Error.



<span style="fuente-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span> **(1,5 puntos )**

In [9]:
# Respuesta
# Importamos las bibliotecas necesarias
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error
from google.colab import drive
drive.mount('/content/drive')
ruta_diamonds = "/content/drive/MyDrive/Colab_Notebooks/prog_datasci_6/" \
                "data/diamonds.csv"
original_df = pd.read_csv(ruta_diamonds)

# Seleccionamos las columnas numéricas para la imputación
columns_to_modify = ["carat", "depth", "table", "price", "x", "y", "z"]
# Creamos una copia del dataset original para introducir valores faltantes
df = original_df.copy()

# Se genera un 20% de datos faltantes aleatorios en las columnas seleccionadas
# para simular un escenario donde los datos tienen valores ausentes.
# Para cada una de las tres políticas (mean, median, most_frequent),
# creamos un imputador y aplicamos esa estrategia a los datos faltantes.
# Para cada columna y cada estrategia, se calcula el Root Mean Square Error
# (RMSE) comparando los valores imputados con los valores reales del
# dataset original.
# Se presenta un DataFrame con los resultados de RMSE para cada estrategia y
# cada variable, lo que permite comparar la efectividad de las tres
# políticas de imputación.
np.random.seed(42)  # Usamos una semilla para reproducibilidad
for column in columns_to_modify:
    n_missing = int(0.2 * len(df[column]))  # Calculamos el 20% de filas
    # Seleccionamos índices aleatorios
    missing_indices = np.random.choice(df.index, n_missing, replace=False)
    # Asignamos NaN en los índices seleccionados
    df.loc[missing_indices, column] = np.nan

# Verificamos el porcentaje de valores faltantes por variable y los imprimimos
missing_percentage = df[columns_to_modify].isnull().mean() * 100
print("\nPorcentaje de valores perdidos por variable:")
print(missing_percentage)

# Definimos las estrategias de imputación a evaluar
strategies = ["mean", "median", "most_frequent"]
# Diccionario para almacenar los resultados de RMSE
rmse_results = {}
# Evaluamos cada estrategia de imputación. strategy es una variable de control
# en este caso, que en cada iteración toma uno de los valores de la lista
# strategies ("mean", "median", o "most_frequent").
for strategy in strategies:
    imputers = {}  # Diccionario para almacenar imputadores por columna
    rmse_results[strategy] = {}  # Diccionario para guardar RMSE por estrategia
    for column in columns_to_modify:
        # Creamos el imputador para la estrategia actual
        imputer = SimpleImputer(strategy=strategy)
        imputers[column] = imputer
        # Aplicamos la imputación a los datos con valores faltantes
        df_imputed = df.copy()  # Trabajamos con una copia del dataset con NaN
        df_imputed[column] = imputer.fit_transform(df[[column]])
        # Identificamos los índices donde realizamos imputación
        valid_indices = original_df[column].notnull() & df[column].isnull()
        # Calculamos el RMSE comparando los valores originales con los imputados
        # valid_indices identifica las filas donde se imputaron valores.
        # mean_squared_error calcula el error cuadrático medio entre los
        # valores reales y los imputados.
        # np.sqrt() toma la raíz cuadrada de ese valor para obtener el RMSE,
        # que es la métrica de rendimiento para evaluar qué tan bien funcionó
        # la imputación en esos índices seleccionados.
        rmse = np.sqrt(
            mean_squared_error(
                original_df.loc[valid_indices, column],  # Valores originales
                df_imputed.loc[valid_indices, column]))   # Valores imputados
        # Guardamos el RMSE en el diccionario de resultados
        # rmse_results[strategy] accede al subdiccionario de resultados para la
        # estrategia de imputación actual ("mean", "median", o "most_frequent")
        # [column] selecciona la clave dentro de ese subdiccionario
        # correspondiente a la columna específica (e.g., "carat").
        # = rmse asigna el valor del RMSE calculado a esa posición
        # específica en el diccionario.
        rmse_results[strategy][column] = rmse
# Convertimos los resultados de RMSE a un DataFrame para mejor visualización
rmse_df = pd.DataFrame(rmse_results)

# Mostramos los resultados finales
print("\nRMSE por estrategia y variable:")
print(rmse_df)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Porcentaje de valores perdidos por variable:
carat    20.0
depth    20.0
table    20.0
price    20.0
x        20.0
y        20.0
z        20.0
dtype: float64

RMSE por estrategia y variable:
              mean       median  most_frequent
carat     0.476681     0.486401       0.688476
depth     1.426011     1.427327       1.450027
table     2.247545     2.298000       2.690773
price  4010.784748  4299.634398    5221.245517
x         1.117129     1.118085       1.765197
y         1.135813     1.135929       1.785843
z         0.694802     0.694902       1.092316


c) Imputar los datos con valores perdidos con la mejor política para cada variable y crear un dataframe llamado `df`. Compruebe que no hay valores perdidos para cada variable


**(1 punto)**  <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 2px; ">NM</span>

In [12]:
# Respuesta
# Utilizamos el df 'rmse_df' que contiene los resultados de RMSE para cada
# estrategia de imputación y columna. Seleccionamos la estrategia con el menor
# RMSE para cada columna (axis=1 se refiere a columnas).
best_policies = rmse_df.idxmin(axis=1)

# Creamos una copia del df original para no modificarlo directamente.
df_imputed = original_df.copy()
# Recorremos cada columna y su respectiva mejor estrategia de imputación
for column, best_strategy in best_policies.items():
    # Creamos un SimpleImputer para cada columna con la estrategia
    # seleccionada en best_strategy. El imputador se utiliza para reemplazar
    # los valores faltantes (NaN) con el valor calculado según
    # la estrategia ('mean', 'median', o 'most_frequent').
    best_imputer = SimpleImputer(strategy=best_strategy)
    # Aplicamos el imputador a la columna seleccionada.
    # fit_transform() es de la librería Scikit-learn, dónde
    # el método fit() se usa para ajustar el imputador a los datos.
    # En este caso, el imputador aprende de los valores no nulos en la columna,
    # y dependiendo de la estrategia seleccionada,
    # calcula el valor que se usará para reemplazar los valores faltantes.
    # El método transform() se usa para aplicar la transformación
    # (en este caso, la imputación) a los datos, i.e., reemplaza los valores
    # faltantes con los valores calculados durante el ajuste (e.g. la media).
    df_imputed[column] = best_imputer.fit_transform(df[[column]])

# Comprobamos que no queden valores perdidos en el df imputado.
# Si todo ha ido bien, el resultado de 'isnull().sum()' será 0 para
# todas las columnas.
print("Valores perdidos por variable después de la imputación:")
print(df_imputed.isnull().sum())

Valores perdidos por variable después de la imputación:
carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64


### Ejercicio Opcional

Los valores atípicos son valores que se alejan del resto de variables y, en la mayoría de los casos, son valores que pueden perturbar el resultado final. Por esta razón es necesario identificarlos y, generalmente, eliminarlos del análisis. Utilizad la función `IsolationForest` de la librería [sklearn.ensemble](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.IsolationForest.html) para determinar los valores atípicos considerando una proporción de valores atípicos en el conjunto de datos de `0.2`. Determina cuantos valores atípicos hay en el conjunto de datos derivados del útimo ejercicio, considerando las variables  `carat`, `depth`, `table`, `price`, `x`, `y`,`z` y que filas deberían de ser eliminados del conjunto de datos final según este criterio.


El [análisis de componentes principales (PCA)](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html) encuentra líneas, planos e hiperplanos en el espacio K-dimensional que se aproximan a los datos lo mejor posible en el sentido de mínimos cuadrados. Una línea o plano que es la aproximación de mínimos cuadrados de un conjunto de puntos de datos hace que la variación de las coordenadas en la línea o plano sea lo más grande posible.
 Realiza un analisis de componentes principales (PCA) y muestra un score plot marcando los valores eliminados.




<span style = "font-family: Courier New; background-color: #f2ae72; color: #000000; padding: 3px;"></span>

Bibliografía

Universitat Oberta de Catalunya. (09/2022). prog_datasci_6_preproc.pdf. https://aula.uoc.edu/courses/47714

PEC6 - Aleem Karim Saeed